import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, it, expect } from 'vitest';
import {
  KEY_COMMIT_DOMAIN,
  MAX_LEAF_SPKI,
  poseidonChunkHashVarT7,
  keyCommit,
} from './key-commit';

// Canonical parity fixture — generated by `scripts/gen-key-commit-parity.ts`
// from this same TS reference impl. Solidity and Circom implementations
// load the SAME file and assert their outputs match these vectors.
//
// Path is relative to the repo root (foundry's fs_permissions are
// scoped to packages/contracts/test/fixtures, so the fixture is
// mirrored there too — see Solidity test).
const FIXTURE_PATH = resolve(
  __dirname,
  '../../../../../fixtures/v5_5/key-commit-parity.json',
);

interface FixtureVector {
  label: string;
  spkiHex: string;
  expectedChunkHash: string;
  expectedKeyCommit: string;
}

interface Fixture {
  notes: string;
  domainLiteral: string;
  domainConstant: string;
  vectors: FixtureVector[];
}

describe('KEY_COMMIT_DOMAIN', () => {
  it('matches the fixture-pinned constant', () => {
    const fix: Fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'));
    expect(KEY_COMMIT_DOMAIN.toString()).toBe(fix.domainConstant);
    expect(fix.domainLiteral).toBe('zkqes-key-commit-v1');
  });
});

describe('poseidonChunkHashVarT7', () => {
  it('rejects inputs longer than MAX_LEAF_SPKI', async () => {
    await expect(
      poseidonChunkHashVarT7(new Uint8Array(MAX_LEAF_SPKI + 1)),
    ).rejects.toThrow(/exceeds MAX_LEAF_SPKI/);
  });

  it('matches all parity vectors', async () => {
    const fix: Fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'));
    for (const v of fix.vectors) {
      const bytes = hexToBytes(v.spkiHex);
      const got = await poseidonChunkHashVarT7(bytes);
      expect(got.toString()).toBe(v.expectedChunkHash);
    }
  });
});

describe('keyCommit', () => {
  it('matches all parity vectors', async () => {
    const fix: Fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'));
    for (const v of fix.vectors) {
      const bytes = hexToBytes(v.spkiHex);
      const got = await keyCommit(bytes);
      expect(got.toString()).toBe(v.expectedKeyCommit);
    }
  });

  it('is deterministic across repeated calls', async () => {
    const data = new Uint8Array(91);
    for (let i = 0; i < data.length; i++) data[i] = i;
    const a = await keyCommit(data);
    const b = await keyCommit(data);
    expect(a).toBe(b);
  });

  it('differs for differing inputs', async () => {
    const a = new Uint8Array(91);
    const b = new Uint8Array(91);
    b[0] = 1;
    expect(await keyCommit(a)).not.toBe(await keyCommit(b));
  });
});

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex;
  if (clean.length % 2 !== 0) throw new Error(`odd-length hex: ${hex}`);
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}
